<?php
use Illuminate\Database\Seeder;
use App\Role;
use App\Permission;
use App\user;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $this->call(loaixesSeeder::class);
        $this->call(chucvusSeeder::class);
        $this->call(usersSeeder::class);
        $this->call(quaysSeeder::class);
        $this->call(loaikhachhangsSeeder::class);
        $this->call(tuyensSeeder::class);
        $this->call(benxesSeeder::class);
        $this->call(nhanviensSeeder::class);
        $this->call(blogsSeeder::class);
    }
}

class blogsSeeder extends Seeder
{
    public function run()
    {
        DB::table('blogs')->insert([
            ['Ten' => 'THÔNG BÁO - VỀ VIỆC TẠM NGƯNG CÁC DỊCH VỤ ĐANG CUNG CẤP TẠI CÔNG TY DO TÌNH HÌNH DỊCH BỆNH COVID-19','NoiDungTomTat' => 'THÔNG BÁO - VỀ VIỆC TẠM NGƯNG CÁC DỊCH VỤ ĐANG CUNG CẤP TẠI CÔNG TY DO TÌNH HÌNH DỊCH BỆNH COVID-19','NoiDung' => 'Nội Dung 1','created_at' => '2021-06-03 13:10:59'],
            ['Ten' => 'THÔNG BÁO UBND THÀNH PHỐ HỒ CHÍ MINH VỀ VIỆC TRIỂN KHAI TĂNG CƯỜNG CÁC BIỆN PHÁP KIỂM SOÁT DỊCH COVID-19 TRÊN ĐỊA BÀN THÀNH PHỐ HỒ CHÍ MINH','NoiDungTomTat' => 'THÔNG BÁO UBND THÀNH PHỐ HỒ CHÍ MINH VỀ VIỆC TRIỂN KHAI TĂNG CƯỜNG CÁC BIỆN PHÁP KIỂM SOÁT DỊCH ...','NoiDung' => 'Nội Dung 2','created_at' => '2021-05-31 13:11:04'],
            ['Ten' => 'THÔNG BÁO - UỶ BAN NHÂN DÂN THÀNH PHỐ HỒ CHÍ MINH VỀ VIỆC TĂNG CƯỜNG TRIỂN KHAI CÁC HOẠT ĐỘNG PHÒNG CHỐNG COVID-19 TRÊN ĐỊA BÀN THÀNH PHỐ HỒ CHÍ MINH','NoiDungTomTat' => 'THÔNG BÁO - UỶ BAN NHÂN DÂN THÀNH PHỐ HỒ CHÍ MINH VỀ VIỆC TĂNG CƯỜNG TRIỂN KHAI CÁC HOẠT ĐỘNG PHÒNG...','NoiDung' => 'Nội Dung 3','created_at' => '2021-05-29 13:11:26'],
            ['Ten' => 'SỞ GIAO THÔNG VẬN TẢI HỒ CHÍ MINH THÔNG BÁO VỀ VIỆC TIẾP TỤC THỰC HIỆN NGHIÊM CÁC BIỆN PHÁP PHÒNG,CHỐNG DỊCH COVID-19 TRÊN ĐỊA BÀN THÀNH PHỐ HỒ CHÍ MINH','NoiDungTomTat' => 'SỞ GIAO THÔNG VẬN TẢI HỒ CHÍ MINH THÔNG BÁO VỀ VIỆC TIẾP TỤC THỰC HIỆN NGHIÊM CÁC BIỆN PHÁP PHÒNG ...','NoiDung' => 'Nội Dung 4','created_at' => '2021-05-29 13:11:26'],
        ]);
    }
}
class usersSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            ['name' => 'quay1','email' => 'quay1@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay2','email' => 'quay2@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay3','email' => 'quay3@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay4','email' => 'quay4@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay5','email' => 'quay5@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay6','email' => 'quay6@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay7','email' => 'quay7@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay8','email' => 'quay8@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay9','email' => 'quay9@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay10','email' => 'quay10@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay11','email' => 'quay11@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay12','email' => 'quay12@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay13','email' => 'quay13@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay14','email' => 'quay14@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay15','email' => 'quay15@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay16','email' => 'quay16@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay17','email' => 'quay17@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay18','email' => 'quay18@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay19','email' => 'quay19@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay20','email' => 'quay20@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay21','email' => 'quay21@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay22','email' => 'quay22@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay23','email' => 'quay23@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay24','email' => 'quay24@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay25','email' => 'quay25@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay26','email' => 'quay26@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay27','email' => 'quay27@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay28','email' => 'quay28@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay29','email' => 'quay29@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay30','email' => 'quay30@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay31','email' => 'quay31@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay32','email' => 'quay32@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay33','email' => 'quay33@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay34','email' => 'quay34@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay35','email' => 'quay35@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay36','email' => 'quay36@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay37','email' => 'quay37@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay38','email' => 'quay38@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay39','email' => 'quay39@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay40','email' => 'quay40@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay41','email' => 'quay41@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay42','email' => 'quay42@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay43','email' => 'quay43@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay44','email' => 'quay44@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay45','email' => 'quay45@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay46','email' => 'quay46@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay47','email' => 'quay47@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay48','email' => 'quay48@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay49','email' => 'quay49@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay50','email' => 'quay50@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay51','email' => 'quay51@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay52','email' => 'quay52@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay53','email' => 'quay53@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay54','email' => 'quay54@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay55','email' => 'quay55@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay56','email' => 'quay56@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay57','email' => 'quay57@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay58','email' => 'quay58@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay59','email' => 'quay59@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay60','email' => 'quay60@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay61','email' => 'quay61@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay62','email' => 'quay62@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay63','email' => 'quay63@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay64','email' => 'quay64@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay65','email' => 'quay65@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay66','email' => 'quay66@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay67','email' => 'quay67@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay68','email' => 'quay68@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay69','email' => 'quay69@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay70','email' => 'quay70@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay71','email' => 'quay71@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay72','email' => 'quay72@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay73','email' => 'quay73@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay74','email' => 'quay74@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay75','email' => 'quay75@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay76','email' => 'quay76@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay77','email' => 'quay77@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay78','email' => 'quay78@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay79','email' => 'quay79@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay80','email' => 'quay80@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay81','email' => 'quay81@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay82','email' => 'quay82@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay83','email' => 'quay83@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay84','email' => 'quay84@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay85','email' => 'quay85@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay86','email' => 'quay86@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay87','email' => 'quay87@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay88','email' => 'quay88@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay89','email' => 'quay89@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay90','email' => 'quay90@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay91','email' => 'quay91@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay92','email' => 'quay92@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay93','email' => 'quay93@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay94','email' => 'quay94@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay95','email' => 'quay95@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay96','email' => 'quay96@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay97','email' => 'quay97@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay98','email' => 'quay98@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'quay99','email' => 'quay99@nhanvien.com','password' => bcrypt('12341234'),'id_ChucVu' => '2'],
            ['name' => 'Admin','email' => 'admin@admin.com','password' => bcrypt('12341234'),'id_ChucVu' => '1'],
        ]);
    }
}
class nhanviensSeeder extends Seeder
{
    public function run()
    {
        DB::table('nhanviens')->insert([
            ['Ten' => 'quay1','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '1', 'id_User' => '1'],
            ['Ten' => 'quay2','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '2', 'id_User' => '2'],
            ['Ten' => 'quay3','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '3', 'id_User' => '3'],
            ['Ten' => 'quay4','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '4', 'id_User' => '4'],
            ['Ten' => 'quay5','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '5', 'id_User' => '5'],
            ['Ten' => 'quay6','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '6', 'id_User' => '6'],
            ['Ten' => 'quay7','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '7', 'id_User' => '7'],
            ['Ten' => 'quay8','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '8', 'id_User' => '8'],
            ['Ten' => 'quay9','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '9', 'id_User' => '9'],
            ['Ten' => 'quay10','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '10', 'id_User' => '10'],
            ['Ten' => 'quay11','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '11', 'id_User' => '11'],
            ['Ten' => 'quay12','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '12', 'id_User' => '12'],
            ['Ten' => 'quay13','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '13', 'id_User' => '13'],
            ['Ten' => 'quay14','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '14', 'id_User' => '14'],
            ['Ten' => 'quay15','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '15', 'id_User' => '15'],
            ['Ten' => 'quay16','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '16', 'id_User' => '16'],
            ['Ten' => 'quay17','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '17', 'id_User' => '17'],
            ['Ten' => 'quay18','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '18', 'id_User' => '18'],
            ['Ten' => 'quay19','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '19', 'id_User' => '19'],
            ['Ten' => 'quay20','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '20', 'id_User' => '20'],
            ['Ten' => 'quay21','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '21', 'id_User' => '21'],
            ['Ten' => 'quay22','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '22', 'id_User' => '22'],
            ['Ten' => 'quay23','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '23', 'id_User' => '23'],
            ['Ten' => 'quay24','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '24', 'id_User' => '24'],
            ['Ten' => 'quay25','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '25', 'id_User' => '25'],
            ['Ten' => 'quay26','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '26', 'id_User' => '26'],
            ['Ten' => 'quay27','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '27', 'id_User' => '27'],
            ['Ten' => 'quay28','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '28', 'id_User' => '28'],
            ['Ten' => 'quay29','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '29', 'id_User' => '29'],
            ['Ten' => 'quay30','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '30', 'id_User' => '30'],
            ['Ten' => 'quay31','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '31', 'id_User' => '31'],
            ['Ten' => 'quay32','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '32', 'id_User' => '32'],
            ['Ten' => 'quay33','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '33', 'id_User' => '33'],
            ['Ten' => 'quay34','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '34', 'id_User' => '34'],
            ['Ten' => 'quay35','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '35', 'id_User' => '35'],
            ['Ten' => 'quay36','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '36', 'id_User' => '36'],
            ['Ten' => 'quay37','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '37', 'id_User' => '37'],
            ['Ten' => 'quay38','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '38', 'id_User' => '38'],
            ['Ten' => 'quay39','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '39', 'id_User' => '39'],
            ['Ten' => 'quay40','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '40', 'id_User' => '40'],
            ['Ten' => 'quay41','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '41', 'id_User' => '41'],
            ['Ten' => 'quay42','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '42', 'id_User' => '42'],
            ['Ten' => 'quay43','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '43', 'id_User' => '43'],
            ['Ten' => 'quay44','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '44', 'id_User' => '44'],
            ['Ten' => 'quay45','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '45', 'id_User' => '45'],
            ['Ten' => 'quay46','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '46', 'id_User' => '46'],
            ['Ten' => 'quay47','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '47', 'id_User' => '47'],
            ['Ten' => 'quay48','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '48', 'id_User' => '48'],
            ['Ten' => 'quay49','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '49', 'id_User' => '49'],
            ['Ten' => 'quay50','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '50', 'id_User' => '50'],
            ['Ten' => 'quay51','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '51', 'id_User' => '51'],
            ['Ten' => 'quay52','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '52', 'id_User' => '52'],
            ['Ten' => 'quay53','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '53', 'id_User' => '53'],
            ['Ten' => 'quay54','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '54', 'id_User' => '54'],
            ['Ten' => 'quay55','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '55', 'id_User' => '55'],
            ['Ten' => 'quay56','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '56', 'id_User' => '56'],
            ['Ten' => 'quay57','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '57', 'id_User' => '57'],
            ['Ten' => 'quay58','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '58', 'id_User' => '58'],
            ['Ten' => 'quay59','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '59', 'id_User' => '59'],
            ['Ten' => 'quay60','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '60', 'id_User' => '60'],
            ['Ten' => 'quay61','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '61', 'id_User' => '61'],
            ['Ten' => 'quay62','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '62', 'id_User' => '62'],
            ['Ten' => 'quay63','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '63', 'id_User' => '63'],
            ['Ten' => 'quay64','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '64', 'id_User' => '64'],
            ['Ten' => 'quay65','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '65', 'id_User' => '65'],
            ['Ten' => 'quay66','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '66', 'id_User' => '66'],
            ['Ten' => 'quay67','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '67', 'id_User' => '67'],
            ['Ten' => 'quay68','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '68', 'id_User' => '68'],
            ['Ten' => 'quay69','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '69', 'id_User' => '69'],
            ['Ten' => 'quay70','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '70', 'id_User' => '70'],
            ['Ten' => 'quay71','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '71', 'id_User' => '71'],
            ['Ten' => 'quay72','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '72', 'id_User' => '72'],
            ['Ten' => 'quay73','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '73', 'id_User' => '73'],
            ['Ten' => 'quay74','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '74', 'id_User' => '74'],
            ['Ten' => 'quay75','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '75', 'id_User' => '75'],
            ['Ten' => 'quay76','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '76', 'id_User' => '76'],
            ['Ten' => 'quay77','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '77', 'id_User' => '77'],
            ['Ten' => 'quay78','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '78', 'id_User' => '78'],
            ['Ten' => 'quay79','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '79', 'id_User' => '79'],
            ['Ten' => 'quay80','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '80', 'id_User' => '80'],
            ['Ten' => 'quay81','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '81', 'id_User' => '81'],
            ['Ten' => 'quay82','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '82', 'id_User' => '82'],
            ['Ten' => 'quay83','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '83', 'id_User' => '83'],
            ['Ten' => 'quay84','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '84', 'id_User' => '84'],
            ['Ten' => 'quay85','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '85', 'id_User' => '85'],
            ['Ten' => 'quay86','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '86', 'id_User' => '86'],
            ['Ten' => 'quay87','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '87', 'id_User' => '87'],
            ['Ten' => 'quay88','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '88', 'id_User' => '88'],
            ['Ten' => 'quay89','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '89', 'id_User' => '89'],
            ['Ten' => 'quay90','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '90', 'id_User' => '90'],
            ['Ten' => 'quay91','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '91', 'id_User' => '91'],
            ['Ten' => 'quay92','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '92', 'id_User' => '92'],
            ['Ten' => 'quay93','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '93', 'id_User' => '93'],
            ['Ten' => 'quay94','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '94', 'id_User' => '94'],
            ['Ten' => 'quay95','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '95', 'id_User' => '95'],
            ['Ten' => 'quay96','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '96', 'id_User' => '96'],
            ['Ten' => 'quay97','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '97', 'id_User' => '97'],
            ['Ten' => 'quay98','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '98', 'id_User' => '98'],
            ['Ten' => 'quay99','NgaySinh' => '1999-05-26','DiaChi' => '123ABC','SDT' => '0123456789', 'NgayBatDauHopDong' => '2021-05-07', 'id_Quay' => '99', 'id_User' => '99'],
        ]);
    }
}
class loaixesSeeder extends Seeder
{
    public function run()
    {
        DB::table('loaixes')->insert([
            ['id' => '1','Ten' => 'Giường Nằm','SoGhe' => '24','SoDoGhe' => "'A1','A2','A3','A4','A5','A6','A7','A8','A9','A10','A11','A12','B1','B2','B3','B4','B5','B6','B7','B8','B9','B10','B11','B12'"],
            ['id' => '2','Ten' => 'Giường Nằm','SoGhe' => '34','SoDoGhe' => "'A1','A2','A3','A4','A5','A6','A7','A8','A9','A10','A11','A12','A13','A14','A15','A16','A17','B1','B2','B3','B4','B5','B6','B7','B8','B9','B10','B11','B12','B13','B14','B15','B16','B17'"],
        ]);
    }
}
class chucvusSeeder extends Seeder
{
    public function run()
    {
        DB::table('chucvus')->insert([
            ['id' => '1','Ten' => 'Admin'],
            ['id' => '2','Ten' => 'Nhân Viên'],
            ['id' => '3','Ten' => 'Nhà Xe'],
            ['id' => '4','Ten' => 'Khách Hàng'],
        ]);
    }
}
class loaikhachhangsSeeder extends Seeder
{
    public function run()
    {
        DB::table('loaikhachhangs')->insert([
            ['id' => '1','Ten' => 'Vãng Lai','GiamGia' => '0'],
            ['id' => '2','Ten' => 'Thân Quen','GiamGia' => '5'],
            ['id' => '3','Ten' => 'Vip','GiamGia' => '10'],
        ]);
    }
}
class quaysSeeder extends Seeder
{
    public function run()
    {
        DB::table('quays')->insert([
            ['Ten' => '1'],
            ['Ten' => '2'],
            ['Ten' => '3'],
            ['Ten' => '4'],
            ['Ten' => '5'],
            ['Ten' => '6'],
            ['Ten' => '7'],
            ['Ten' => '8'],
            ['Ten' => '9'],
            ['Ten' => '10'],
            ['Ten' => '11'],
            ['Ten' => '12'],
            ['Ten' => '13'],
            ['Ten' => '14'],
            ['Ten' => '15'],
            ['Ten' => '16'],
            ['Ten' => '17'],
            ['Ten' => '18'],
            ['Ten' => '19'],
            ['Ten' => '20'],
            ['Ten' => '21'],
            ['Ten' => '22'],
            ['Ten' => '23'],
            ['Ten' => '24'],
            ['Ten' => '25'],
            ['Ten' => '26'],
            ['Ten' => '27'],
            ['Ten' => '28'],
            ['Ten' => '29'],
            ['Ten' => '30'],
            ['Ten' => '31'],
            ['Ten' => '32'],
            ['Ten' => '33'],
            ['Ten' => '34'],
            ['Ten' => '35'],
            ['Ten' => '36'],
            ['Ten' => '37'],
            ['Ten' => '38'],
            ['Ten' => '39'],
            ['Ten' => '40'],
            ['Ten' => '41'],
            ['Ten' => '42'],
            ['Ten' => '43'],
            ['Ten' => '44'],
            ['Ten' => '45'],
            ['Ten' => '46'],
            ['Ten' => '47'],
            ['Ten' => '48'],
            ['Ten' => '49'],
            ['Ten' => '50'],
            ['Ten' => '51'],
            ['Ten' => '52'],
            ['Ten' => '53'],
            ['Ten' => '54'],
            ['Ten' => '55'],
            ['Ten' => '56'],
            ['Ten' => '57'],
            ['Ten' => '58'],
            ['Ten' => '59'],
            ['Ten' => '60'],
            ['Ten' => '61'],
            ['Ten' => '62'],
            ['Ten' => '63'],
            ['Ten' => '64'],
            ['Ten' => '65'],
            ['Ten' => '66'],
            ['Ten' => '67'],
            ['Ten' => '68'],
            ['Ten' => '69'],
            ['Ten' => '70'],
            ['Ten' => '71'],
            ['Ten' => '72'],
            ['Ten' => '73'],
            ['Ten' => '74'],
            ['Ten' => '75'],
            ['Ten' => '76'],
            ['Ten' => '77'],
            ['Ten' => '78'],
            ['Ten' => '79'],
            ['Ten' => '80'],
            ['Ten' => '81'],
            ['Ten' => '82'],
            ['Ten' => '83'],
            ['Ten' => '84'],
            ['Ten' => '85'],
            ['Ten' => '86'],
            ['Ten' => '87'],
            ['Ten' => '88'],
            ['Ten' => '89'],
            ['Ten' => '90'],
            ['Ten' => '91'],
            ['Ten' => '92'],
            ['Ten' => '93'],
            ['Ten' => '94'],
            ['Ten' => '95'],
            ['Ten' => '96'],
            ['Ten' => '97'],
            ['Ten' => '98'],
            ['Ten' => '99'],
        ]);
    }
}
class tuyensSeeder extends Seeder
{
    public function run()
    {
        DB::table('tuyens')->insert([
            ['id' => '1','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'An Giang','DoDai' => '1'],
            ['id' => '2','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Bà Rịa Vũng Tàu','DoDai' => '1'],
            ['id' => '3','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Bắc Cạn','DoDai' => '1'],
            ['id' => '4','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Bắc Giang','DoDai' => '1'],
            ['id' => '5','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Bắc Ninh','DoDai' => '1'],
            ['id' => '6','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Bến Tre','DoDai' => '1'],
            ['id' => '7','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Bình Dương','DoDai' => '1'],
            ['id' => '8','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Bình Phước','DoDai' => '1'],
            ['id' => '9','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Bình Thuận','DoDai' => '1'],
            ['id' => '10','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Bình Định','DoDai' => '1'],
            ['id' => '11','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Buôn Ma Thuột','DoDai' => '1'],
            ['id' => '12','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Cà Mau','DoDai' => '1'],
            ['id' => '13','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Cao Bằng','DoDai' => '1'],
            ['id' => '14','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Gia Lai','DoDai' => '1'],
            ['id' => '15','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Hà Giang','DoDai' => '1'],
            ['id' => '16','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Hà Nam','DoDai' => '1'],
            ['id' => '17','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Hà Tây','DoDai' => '1'],
            ['id' => '18','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Hà Tĩnh','DoDai' => '1'],
            ['id' => '19','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Hải Dương','DoDai' => '1'],
            ['id' => '20','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Hải Phòng','DoDai' => '1'],
            ['id' => '21','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Hậu Giang','DoDai' => '1'],
            ['id' => '22','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Hòa Bình','DoDai' => '1'],
            ['id' => '23','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Huế','DoDai' => '1'],
            ['id' => '24','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Hưng Yên','DoDai' => '1'],
            ['id' => '25','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Khánh Hòa','DoDai' => '1'],
            ['id' => '26','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Kiên Giang','DoDai' => '1'],
            ['id' => '27','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Kon Tum','DoDai' => '1'],
            ['id' => '28','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Lai Châu','DoDai' => '1'],
            ['id' => '29','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Lâm Đồng','DoDai' => '1'],
            ['id' => '30','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Lạng Sơn','DoDai' => '1'],
            ['id' => '31','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Lào Cai','DoDai' => '1'],
            ['id' => '32','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Nam Định','DoDai' => '1'],
            ['id' => '33','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Nghệ An','DoDai' => '1'],
            ['id' => '34','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Ninh Bình','DoDai' => '1'],
            ['id' => '35','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Ninh Thuận','DoDai' => '1'],
            ['id' => '36','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Pắc Sế','DoDai' => '1'],
            ['id' => '37','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Phú Thọ','DoDai' => '1'],
            ['id' => '38','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Phú Yên','DoDai' => '1'],
            ['id' => '39','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Quảng Bình','DoDai' => '1'],
            ['id' => '40','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Quảng Nam','DoDai' => '1'],
            ['id' => '41','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Quảng Ngãi','DoDai' => '1'],
            ['id' => '42','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Quảng Ninh','DoDai' => '1'],
            ['id' => '43','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Quảng Trị','DoDai' => '1'],
            ['id' => '44','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Sóc Trăng','DoDai' => '1'],
            ['id' => '45','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Sơn La','DoDai' => '1'],
            ['id' => '46','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Tây Ninh','DoDai' => '1'],
            ['id' => '47','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Thái Bình','DoDai' => '1'],
            ['id' => '48','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Thanh Hóa','DoDai' => '1'],
            ['id' => '49','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'TP. Hà Nội','DoDai' => '1'],
            ['id' => '50','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'TP. Đà Nẵng','DoDai' => '1'],
            ['id' => '51','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Trà Vinh','DoDai' => '1'],
            ['id' => '52','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Tuyên Quang','DoDai' => '1'],
            ['id' => '53','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Viêng Chăn','DoDai' => '1'],
            ['id' => '54','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Vĩnh Phúc','DoDai' => '1'],
            ['id' => '55','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Yên Bái','DoDai' => '1'],
            ['id' => '56','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Đắk Lắk','DoDai' => '1'],
            ['id' => '57','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Đắk Nông','DoDai' => '1'],
            ['id' => '58','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Điện Biên','DoDai' => '1'],
            ['id' => '59','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Đồng Nai','DoDai' => '1'],

            ['id' => '60','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'An Giang','DoDai' => '1'],
            ['id' => '61','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Bà Rịa Vũng Tàu','DoDai' => '1'],
            ['id' => '62','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Bắc Cạn','DoDai' => '1'],
            ['id' => '63','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Bắc Giang','DoDai' => '1'],
            ['id' => '64','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Bắc Ninh','DoDai' => '1'],
            ['id' => '65','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Bến Tre','DoDai' => '1'],
            ['id' => '66','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Bình Dương','DoDai' => '1'],
            ['id' => '67','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Bình Phước','DoDai' => '1'],
            ['id' => '68','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Bình Thuận','DoDai' => '1'],
            ['id' => '69','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Bình Định','DoDai' => '1'],
            ['id' => '70','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Buôn Ma Thuột','DoDai' => '1'],
            ['id' => '71','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Cà Mau','DoDai' => '1'],
            ['id' => '72','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Cao Bằng','DoDai' => '1'],
            ['id' => '73','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Gia Lai','DoDai' => '1'],
            ['id' => '74','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Hà Giang','DoDai' => '1'],
            ['id' => '75','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Hà Nam','DoDai' => '1'],
            ['id' => '76','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Hà Tây','DoDai' => '1'],
            ['id' => '77','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Hà Tĩnh','DoDai' => '1'],
            ['id' => '78','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Hải Dương','DoDai' => '1'],
            ['id' => '79','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Hải Phòng','DoDai' => '1'],
            ['id' => '80','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Hậu Giang','DoDai' => '1'],
            ['id' => '81','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Hòa Bình','DoDai' => '1'],
            ['id' => '82','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Huế','DoDai' => '1'],
            ['id' => '83','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Hưng Yên','DoDai' => '1'],
            ['id' => '84','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Khánh Hòa','DoDai' => '1'],
            ['id' => '85','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Kiên Giang','DoDai' => '1'],
            ['id' => '86','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Kon Tum','DoDai' => '1'],
            ['id' => '87','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Lai Châu','DoDai' => '1'],
            ['id' => '88','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Lâm Đồng','DoDai' => '1'],
            ['id' => '89','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Lạng Sơn','DoDai' => '1'],
            ['id' => '90','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Lào Cai','DoDai' => '1'],
            ['id' => '91','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Nam Định','DoDai' => '1'],
            ['id' => '92','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Nghệ An','DoDai' => '1'],
            ['id' => '93','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Ninh Bình','DoDai' => '1'],
            ['id' => '94','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Ninh Thuận','DoDai' => '1'],
            ['id' => '95','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Pắc Sế','DoDai' => '1'],
            ['id' => '96','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Phú Thọ','DoDai' => '1'],
            ['id' => '97','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Phú Yên','DoDai' => '1'],
            ['id' => '98','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Quảng Bình','DoDai' => '1'],
            ['id' => '99','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Quảng Nam','DoDai' => '1'],
            ['id' => '100','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Quảng Ngãi','DoDai' => '1'],
            ['id' => '101','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Quảng Ninh','DoDai' => '1'],
            ['id' => '102','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Quảng Trị','DoDai' => '1'],
            ['id' => '103','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Sóc Trăng','DoDai' => '1'],
            ['id' => '104','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Sơn La','DoDai' => '1'],
            ['id' => '105','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Tây Ninh','DoDai' => '1'],
            ['id' => '106','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Thái Bình','DoDai' => '1'],
            ['id' => '107','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Thanh Hóa','DoDai' => '1'],
            ['id' => '108','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'TP. Hà Nội','DoDai' => '1'],
            ['id' => '109','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'TP. Đà Nẵng','DoDai' => '1'],
            ['id' => '110','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Trà Vinh','DoDai' => '1'],
            ['id' => '111','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Tuyên Quang','DoDai' => '1'],
            ['id' => '112','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Viêng Chăn','DoDai' => '1'],
            ['id' => '113','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Vĩnh Phúc','DoDai' => '1'],
            ['id' => '114','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Yên Bái','DoDai' => '1'],
            ['id' => '115','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Đắk Lắk','DoDai' => '1'],
            ['id' => '116','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Đắk Nông','DoDai' => '1'],
            ['id' => '117','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Điện Biên','DoDai' => '1'],
            ['id' => '118','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Đồng Nai','DoDai' => '1'],

            ['id' => '119','DiaDiem1' => 'Bến xe Miền Đông','DiaDiem2' => 'Thái Nguyên','DoDai' => '1'],
            ['id' => '120','DiaDiem2' => 'Bến xe Miền Đông','DiaDiem1' => 'Thái Nguyên','DoDai' => '1'],
        ]);
    }
}
class benxesSeeder extends Seeder
{
    public function run()
    {
        DB::table('benxes')->insert([
            ['Ten' => 'Châu Đốc','id_Tuyen' => '1'],
            ['Ten' => 'Châu Đốc','id_Tuyen' => '60'],

            ['Ten' => 'Xuyên Mộc','id_Tuyen' => '2'],
            ['Ten' => 'Châu Đức','id_Tuyen' => '2'],
            ['Ten' => 'Long Hải','id_Tuyen' => '2'],
            ['Ten' => 'Bà Rịa','id_Tuyen' => '2'],
            ['Ten' => 'Vũng Tàu','id_Tuyen' => '2'],
            ['Ten' => 'Xuyên Mộc','id_Tuyen' => '61'],
            ['Ten' => 'Châu Đức','id_Tuyen' => '61'],
            ['Ten' => 'Long Hải','id_Tuyen' => '61'],
            ['Ten' => 'Bà Rịa','id_Tuyen' => '61'],
            ['Ten' => 'Vũng Tàu','id_Tuyen' => '61'],

            ['Ten' => 'Bắc Cạn','id_Tuyen' => '3'],
            ['Ten' => 'Bắc Cạn','id_Tuyen' => '62'],

            ['Ten' => 'Bắc Giang (Bến xe An Châu)','id_Tuyen' => '4'],
            ['Ten' => 'Bắc Giang (Bến xe An Châu)','id_Tuyen' => '63'],

            ['Ten' => 'Bắc Ninh','id_Tuyen' => '5'],
            ['Ten' => 'Bắc Ninh','id_Tuyen' => '64'],

            ['Ten' => 'Thạnh Phú','id_Tuyen' => '6'],
            ['Ten' => 'Thạnh Phú','id_Tuyen' => '65'],

            ['Ten' => 'Thủ Dầu Một','id_Tuyen' => '7'],
            ['Ten' => 'Thị Tính','id_Tuyen' => '7'],
            ['Ten' => 'Tân Uyên','id_Tuyen' => '7'],
            ['Ten' => 'Tân Định','id_Tuyen' => '7'],
            ['Ten' => 'Minh Tân','id_Tuyen' => '7'],
            ['Ten' => 'Dầu Tiếng','id_Tuyen' => '7'],
            ['Ten' => 'Thủ Dầu Một','id_Tuyen' => '66'],
            ['Ten' => 'Thị Tính','id_Tuyen' => '66'],
            ['Ten' => 'Tân Uyên','id_Tuyen' => '66'],
            ['Ten' => 'Tân Định','id_Tuyen' => '66'],
            ['Ten' => 'Minh Tân','id_Tuyen' => '66'],
            ['Ten' => 'Dầu Tiếng','id_Tuyen' => '66'],

            ['Ten' => 'Bình Thắng (Bù Gia Mập)','id_Tuyen' => '8'],
            ['Ten' => 'Phú Văn (Bù Gia Mập)','id_Tuyen' => '8'],
            ['Ten' => 'Phước Long','id_Tuyen' => '8'],
            ['Ten' => 'Đồng Xoài','id_Tuyen' => '8'],
            ['Ten' => 'Lộc Ninh','id_Tuyen' => '8'],
            ['Ten' => 'Chơn Thành','id_Tuyen' => '8'],
            ['Ten' => 'Bù Đốp (Cần Đơn)','id_Tuyen' => '8'],
            ['Ten' => 'Bù Đốp','id_Tuyen' => '8'],
            ['Ten' => 'Bù Đăng','id_Tuyen' => '8'],
            ['Ten' => 'Bù Gia Mập','id_Tuyen' => '8'],
            ['Ten' => 'Bình Long','id_Tuyen' => '8'],
            ['Ten' => 'Bình Thắng (Bù Gia Mập)','id_Tuyen' => '67'],
            ['Ten' => 'Phú Văn (Bù Gia Mập)','id_Tuyen' => '67'],
            ['Ten' => 'Phước Long','id_Tuyen' => '67'],
            ['Ten' => 'Đồng Xoài','id_Tuyen' => '67'],
            ['Ten' => 'Lộc Ninh','id_Tuyen' => '67'],
            ['Ten' => 'Chơn Thành','id_Tuyen' => '67'],
            ['Ten' => 'Bù Đốp (Cần Đơn)','id_Tuyen' => '67'],
            ['Ten' => 'Bù Đốp','id_Tuyen' => '67'],
            ['Ten' => 'Bù Đăng','id_Tuyen' => '67'],
            ['Ten' => 'Bù Gia Mập','id_Tuyen' => '67'],
            ['Ten' => 'Bình Long','id_Tuyen' => '67'],
            
            ['Ten' => 'Bắc Ruộng (Mê Pu)','id_Tuyen' => '9'],
            ['Ten' => 'Bắc Ruộng (Gia An)','id_Tuyen' => '9'],
            ['Ten' => 'Bắc Ruộng (Quốc lộ 20)','id_Tuyen' => '9'],
            ['Ten' => 'Bắc Ruộng (Căn cứ 6)','id_Tuyen' => '9'],
            ['Ten' => 'Ma Lâm','id_Tuyen' => '9'],
            ['Ten' => 'Tánh Linh','id_Tuyen' => '9'],
            ['Ten' => 'Phan Thiết','id_Tuyen' => '9'],
            ['Ten' => 'Phan Ri','id_Tuyen' => '9'],
            ['Ten' => 'Đức Linh','id_Tuyen' => '9'],
            ['Ten' => 'Mũi Né','id_Tuyen' => '9'],
            ['Ten' => 'Liên Hương','id_Tuyen' => '9'],
            ['Ten' => 'Hàm Tân','id_Tuyen' => '9'],
            ['Ten' => 'Chợ Lầu','id_Tuyen' => '9'],
            ['Ten' => 'Bắc Ruộng (Mê Pu)','id_Tuyen' => '68'],
            ['Ten' => 'Bắc Ruộng (Gia An)','id_Tuyen' => '68'],
            ['Ten' => 'Bắc Ruộng (Quốc lộ 20)','id_Tuyen' => '68'],
            ['Ten' => 'Bắc Ruộng (Căn cứ 6)','id_Tuyen' => '68'],
            ['Ten' => 'Ma Lâm','id_Tuyen' => '68'],
            ['Ten' => 'Tánh Linh','id_Tuyen' => '68'],
            ['Ten' => 'Phan Thiết','id_Tuyen' => '68'],
            ['Ten' => 'Phan Ri','id_Tuyen' => '68'],
            ['Ten' => 'Đức Linh','id_Tuyen' => '68'],
            ['Ten' => 'Mũi Né','id_Tuyen' => '68'],
            ['Ten' => 'Liên Hương','id_Tuyen' => '68'],
            ['Ten' => 'Hàm Tân','id_Tuyen' => '68'],
            ['Ten' => 'Chợ Lầu','id_Tuyen' => '68'],
            
            ['Ten' => 'Tây Sơn (Phú Phong)','id_Tuyen' => '10'],
            ['Ten' => 'Phú Mỹ (Bình Dương)','id_Tuyen' => '10'],
            ['Ten' => 'Tây Sơn (Bến xe Phú Phong)','id_Tuyen' => '10'],
            ['Ten' => 'Phú Mỹ','id_Tuyen' => '10'],
            ['Ten' => 'Phù Cát','id_Tuyen' => '10'],
            ['Ten' => 'Quy Nhơn','id_Tuyen' => '10'],
            ['Ten' => 'Bồng Sơn','id_Tuyen' => '10'],
            ['Ten' => 'An Nhơn','id_Tuyen' => '10'],
            ['Ten' => 'Tây Sơn (Phú Phong)','id_Tuyen' => '69'],
            ['Ten' => 'Phú Mỹ (Bình Dương)','id_Tuyen' => '69'],
            ['Ten' => 'Tây Sơn (Bến xe Phú Phong)','id_Tuyen' => '69'],
            ['Ten' => 'Phú Mỹ','id_Tuyen' => '69'],
            ['Ten' => 'Phù Cát','id_Tuyen' => '69'],
            ['Ten' => 'Quy Nhơn','id_Tuyen' => '69'],
            ['Ten' => 'Bồng Sơn','id_Tuyen' => '69'],
            ['Ten' => 'An Nhơn','id_Tuyen' => '69'],
            
            ['Ten' => 'Buôn Mê Thuột','id_Tuyen' => '11'],
            ['Ten' => 'Buôn Mê Thuột','id_Tuyen' => '70'],

            ['Ten' => 'Cà Mau','id_Tuyen' => '12'],
            ['Ten' => 'Cà Mau','id_Tuyen' => '71'],

            ['Ten' => 'Cao Bằng','id_Tuyen' => '13'],
            ['Ten' => 'Cao Bằng','id_Tuyen' => '72'],
            
            ['Ten' => 'Đắk Đoa','id_Tuyen' => '14'],
            ['Ten' => 'An Khê','id_Tuyen' => '14'],
            ['Ten' => 'Ayunpa','id_Tuyen' => '14'],
            ['Ten' => 'Chư Sê','id_Tuyen' => '14'],
            ['Ten' => 'Ialy','id_Tuyen' => '14'],
            ['Ten' => "K'Bang",'id_Tuyen' => '14'],
            ['Ten' => 'Krông Pa','id_Tuyen' => '14'],
            ['Ten' => 'Đức Cơ','id_Tuyen' => '14'],
            ['Ten' => 'Đức Long (Pleiku)','id_Tuyen' => '14'],
            ['Ten' => 'Đắk Đoa','id_Tuyen' => '73'],
            ['Ten' => 'An Khê','id_Tuyen' => '73'],
            ['Ten' => 'Ayunpa','id_Tuyen' => '73'],
            ['Ten' => 'Chư Sê','id_Tuyen' => '73'],
            ['Ten' => 'Ialy','id_Tuyen' => '73'],
            ['Ten' => "K'Bang",'id_Tuyen' => '73'],
            ['Ten' => 'Krông Pa','id_Tuyen' => '73'],
            ['Ten' => 'Đức Cơ','id_Tuyen' => '73'],
            ['Ten' => 'Đức Long (Pleiku)','id_Tuyen' => '73'],

            ['Ten' => 'Hà Giang','id_Tuyen' => '15'],
            ['Ten' => 'Hà Giang','id_Tuyen' => '74'],
            
            ['Ten' => 'Hà Nam','id_Tuyen' => '16'],
            ['Ten' => 'Hà Nam','id_Tuyen' => '75'],

            ['Ten' => 'Hà Tây','id_Tuyen' => '17'],
            ['Ten' => 'Hà Tây','id_Tuyen' => '76'],

            ['Ten' => 'Hà Tĩnh','id_Tuyen' => '18'],
            ['Ten' => 'Hà Tĩnh','id_Tuyen' => '77'],

            ['Ten' => 'Hải Dương','id_Tuyen' => '19'],
            ['Ten' => 'Hải Dương','id_Tuyen' => '78'],

            ['Ten' => 'Tam Bạc','id_Tuyen' => '20'],
            ['Ten' => 'Hải Phòng','id_Tuyen' => '20'],
            ['Ten' => 'Cầu Rào','id_Tuyen' => '20'],
            ['Ten' => 'Tam Bạc','id_Tuyen' => '79'],
            ['Ten' => 'Hải Phòng','id_Tuyen' => '79'],
            ['Ten' => 'Cầu Rào','id_Tuyen' => '79'],

            ['Ten' => 'Hậu Giang','id_Tuyen' => '21'],
            ['Ten' => 'Hậu Giang','id_Tuyen' => '80'],

            ['Ten' => 'Hòa Bình','id_Tuyen' => '22'],
            ['Ten' => 'Hòa Bình','id_Tuyen' => '81'],

            ['Ten' => 'Vĩnh Hưng (Thừa Thiên Huế)','id_Tuyen' => '23'],
            ['Ten' => 'Thừa Thiên Huế','id_Tuyen' => '23'],
            ['Ten' => 'Vĩnh Hưng (Thừa Thiên Huế)','id_Tuyen' => '82'],
            ['Ten' => 'Thừa Thiên Huế','id_Tuyen' => '82'],

            ['Ten' => 'Hưng Yên','id_Tuyen' => '24'],
            ['Ten' => 'Triều Dương','id_Tuyen' => '24'],
            ['Ten' => 'Hưng Yên','id_Tuyen' => '83'],
            ['Ten' => 'Triều Dương','id_Tuyen' => '83'],

            ['Ten' => 'Vạn Giã','id_Tuyen' => '25'],
            ['Ten' => 'Ninh Hòa','id_Tuyen' => '25'],
            ['Ten' => 'Nha Trang','id_Tuyen' => '25'],
            ['Ten' => 'Cam Ranh','id_Tuyen' => '25'],
            ['Ten' => 'Vạn Giã','id_Tuyen' => '84'],
            ['Ten' => 'Ninh Hòa','id_Tuyen' => '84'],
            ['Ten' => 'Nha Trang','id_Tuyen' => '84'],
            ['Ten' => 'Cam Ranh','id_Tuyen' => '84'],

            ['Ten' => 'Kiên Giang','id_Tuyen' => '26'],
            ['Ten' => 'Kiên Giang','id_Tuyen' => '85'],

            ['Ten' => 'Ngọc Hồi','id_Tuyen' => '27'],
            ['Ten' => 'Kon Tum','id_Tuyen' => '27'],
            ['Ten' => 'Đắk Hà','id_Tuyen' => '27'],
            ['Ten' => 'Ngọc Hồi','id_Tuyen' => '86'],
            ['Ten' => 'Kon Tum','id_Tuyen' => '86'],
            ['Ten' => 'Đắk Hà','id_Tuyen' => '86'],

            ['Ten' => 'Lai Châu','id_Tuyen' => '28'],
            ['Ten' => 'Lai Châu','id_Tuyen' => '87'],

            ['Ten' => 'Đức Trọng','id_Tuyen' => '29'],
            ['Ten' => 'Đà Lạt','id_Tuyen' => '29'],
            ['Ten' => 'Đạ Tẻh','id_Tuyen' => '29'],
            ['Ten' => 'Đạ Huoai','id_Tuyen' => '29'],
            ['Ten' => 'Cát Tiên','id_Tuyen' => '29'],
            ['Ten' => 'Bảo Lộc','id_Tuyen' => '29'],
            ['Ten' => 'Đức Trọng','id_Tuyen' => '88'],
            ['Ten' => 'Đà Lạt','id_Tuyen' => '88'],
            ['Ten' => 'Đạ Tẻh','id_Tuyen' => '88'],
            ['Ten' => 'Đạ Huoai','id_Tuyen' => '88'],
            ['Ten' => 'Cát Tiên','id_Tuyen' => '88'],
            ['Ten' => 'Bảo Lộc','id_Tuyen' => '88'],

            ['Ten' => 'Lạng Sơn','id_Tuyen' => '30'],
            ['Ten' => 'Lạng Sơn','id_Tuyen' => '89'],

            ['Ten' => 'Lào Cai','id_Tuyen' => '31'],
            ['Ten' => 'Lào Cai','id_Tuyen' => '90'],

            ['Ten' => 'Xuân Trường','id_Tuyen' => '32'],
            ['Ten' => 'Trực Ninh','id_Tuyen' => '32'],
            ['Ten' => 'Nam Định','id_Tuyen' => '32'],
            ['Ten' => 'Hải Hậu','id_Tuyen' => '32'],
            ['Ten' => 'Giao Thủy','id_Tuyen' => '32'],
            ['Ten' => 'Xuân Trường','id_Tuyen' => '91'],
            ['Ten' => 'Trực Ninh','id_Tuyen' => '91'],
            ['Ten' => 'Nam Định','id_Tuyen' => '91'],
            ['Ten' => 'Hải Hậu','id_Tuyen' => '91'],
            ['Ten' => 'Giao Thủy','id_Tuyen' => '91'],

            ['Ten' => 'Vinh','id_Tuyen' => '33'],
            ['Ten' => 'Vinh','id_Tuyen' => '92'],

            ['Ten' => 'Ninh Bình','id_Tuyen' => '34'],
            ['Ten' => 'Ninh Bình','id_Tuyen' => '93'],

            ['Ten' => 'Quảng Sơn (Bến xe Ninh Sơn)','id_Tuyen' => '35'],
            ['Ten' => 'Phan Rang','id_Tuyen' => '35'],
            ['Ten' => 'Quảng Sơn (Bến xe Ninh Sơn)','id_Tuyen' => '94'],
            ['Ten' => 'Phan Rang','id_Tuyen' => '94'],

            ['Ten' => 'Pắc Sế','id_Tuyen' => '36'],
            ['Ten' => 'Pắc Sế','id_Tuyen' => '95'],

            ['Ten' => 'Phú Thọ (Bến xe Việt Trì)','id_Tuyen' => '37'],
            ['Ten' => 'Phú Thọ (Bến xe Việt Trì)','id_Tuyen' => '96'],

            ['Ten' => 'Chí Thạnh (Phú Yên)','id_Tuyen' => '38'],
            ['Ten' => 'Sông Cầu','id_Tuyen' => '38'],
            ['Ten' => 'Sông Hinh','id_Tuyen' => '38'],
            ['Ten' => 'Sơn Hòa','id_Tuyen' => '38'],
            ['Ten' => 'Tuy Hòa','id_Tuyen' => '38'],
            ['Ten' => 'Chí Thạnh (Phú Yên)','id_Tuyen' => '97'],
            ['Ten' => 'Sông Cầu','id_Tuyen' => '97'],
            ['Ten' => 'Sông Hinh','id_Tuyen' => '97'],
            ['Ten' => 'Sơn Hòa','id_Tuyen' => '97'],
            ['Ten' => 'Tuy Hòa','id_Tuyen' => '97'],

            ['Ten' => 'Quy Đạt (Quảng Bình)','id_Tuyen' => '39'],
            ['Ten' => 'Đồng Hới','id_Tuyen' => '39'],
            ['Ten' => 'Lệ Thủy','id_Tuyen' => '39'],
            ['Ten' => 'Hoàn Lão','id_Tuyen' => '39'],
            ['Ten' => 'Ba Đồn','id_Tuyen' => '39'],
            ['Ten' => 'Quy Đạt (Quảng Bình)','id_Tuyen' => '98'],
            ['Ten' => 'Đồng Hới','id_Tuyen' => '98'],
            ['Ten' => 'Lệ Thủy','id_Tuyen' => '98'],
            ['Ten' => 'Hoàn Lão','id_Tuyen' => '98'],
            ['Ten' => 'Ba Đồn','id_Tuyen' => '98'],

            ['Ten' => 'Đại Lộc','id_Tuyen' => '40'],
            ['Ten' => 'Hội An','id_Tuyen' => '40'],
            ['Ten' => 'Quảng Nam','id_Tuyen' => '40'],
            ['Ten' => 'Đại Lộc','id_Tuyen' => '99'],
            ['Ten' => 'Hội An','id_Tuyen' => '99'],
            ['Ten' => 'Quảng Nam','id_Tuyen' => '99'],

            ['Ten' => 'Quảng Ngãi','id_Tuyen' => '41'],
            ['Ten' => 'Đức Phổ','id_Tuyen' => '41'],
            ['Ten' => 'Quảng Ngãi','id_Tuyen' => '100'],
            ['Ten' => 'Đức Phổ','id_Tuyen' => '100'],

            ['Ten' => 'Cửa Ông','id_Tuyen' => '42'],
            ['Ten' => 'Hòn Gai','id_Tuyen' => '42'],
            ['Ten' => 'Cửa Ông','id_Tuyen' => '101'],
            ['Ten' => 'Hòn Gai','id_Tuyen' => '101'],

            ['Ten' => 'Quảng Trị','id_Tuyen' => '43'],
            ['Ten' => 'Đông Hà','id_Tuyen' => '43'],
            ['Ten' => 'Quảng Trị','id_Tuyen' => '102'],
            ['Ten' => 'Đông Hà','id_Tuyen' => '102'],

            ['Ten' => 'Sóc Trăng','id_Tuyen' => '44'],
            ['Ten' => 'Sóc Trăng','id_Tuyen' => '103'],

            ['Ten' => 'Sơn La','id_Tuyen' => '45'],
            ['Ten' => 'Sơn La','id_Tuyen' => '104'],

            ['Ten' => 'Tây Ninh','id_Tuyen' => '46'],
            ['Ten' => 'Tây Ninh','id_Tuyen' => '105'],

            ['Ten' => 'Hoàng Hà (Thái Bình)','id_Tuyen' => '47'],
            ['Ten' => 'Hưng Hà (Thái Bình)','id_Tuyen' => '47'],
            ['Ten' => 'Thái Bình (Bến xe Kiến Xương)','id_Tuyen' => '47'],
            ['Ten' => 'Hoàng Hà (Thái Bình)','id_Tuyen' => '106'],
            ['Ten' => 'Hưng Hà (Thái Bình)','id_Tuyen' => '106'],
            ['Ten' => 'Thái Bình (Bến xe Kiến Xương)','id_Tuyen' => '106'],

            ['Ten' => 'Thái Nguyên','id_Tuyen' => '119'],
            ['Ten' => 'Thái Nguyên','id_Tuyen' => '120'],

            ['Ten' => 'Thanh Hóa','id_Tuyen' => '48'],
            ['Ten' => 'Vĩnh Lộc (Thanh Hóa)','id_Tuyen' => '48'],
            ['Ten' => 'Thanh Hóa','id_Tuyen' => '107'],
            ['Ten' => 'Vĩnh Lộc (Thanh Hóa)','id_Tuyen' => '107'],

            ['Ten' => 'Sơn Tây','id_Tuyen' => '49'],
            ['Ten' => 'Yên Nghĩa','id_Tuyen' => '49'],
            ['Ten' => 'Nước Ngầm','id_Tuyen' => '49'],
            ['Ten' => 'Lương Yên','id_Tuyen' => '49'],
            ['Ten' => 'Hà Tây','id_Tuyen' => '49'],
            ['Ten' => 'Giáp Bát','id_Tuyen' => '49'],
            ['Ten' => 'Sơn Tây','id_Tuyen' => '108'],
            ['Ten' => 'Yên Nghĩa','id_Tuyen' => '108'],
            ['Ten' => 'Nước Ngầm','id_Tuyen' => '108'],
            ['Ten' => 'Lương Yên','id_Tuyen' => '108'],
            ['Ten' => 'Hà Tây','id_Tuyen' => '108'],
            ['Ten' => 'Giáp Bát','id_Tuyen' => '108'],

            ['Ten' => 'Đà Nẵng','id_Tuyen' => '50'],
            ['Ten' => 'Đà Nẵng','id_Tuyen' => '109'],

            ['Ten' => 'Trà Vinh','id_Tuyen' => '51'],
            ['Ten' => 'Trà Vinh','id_Tuyen' => '110'],

            ['Ten' => 'Tuyên Quang','id_Tuyen' => '52'],
            ['Ten' => 'Tuyên Quang','id_Tuyen' => '111'],

            ['Ten' => 'Viêng Chăn','id_Tuyen' => '53'],
            ['Ten' => 'Viêng Chăn','id_Tuyen' => '112'],

            ['Ten' => 'Vĩnh Phúc (Bến xe Lập Thạch)','id_Tuyen' => '54'],
            ['Ten' => 'Vĩnh Phúc (Bến xe Lập Thạch)','id_Tuyen' => '113'],

            ['Ten' => 'Yên Bái','id_Tuyen' => '55'],
            ['Ten' => 'Yên Bái','id_Tuyen' => '114'],

            ['Ten' => 'Quyết Thắng (Krông Pắk)','id_Tuyen' => '56'],
            ['Ten' => 'TP. Buôn Ma Thuột','id_Tuyen' => '56'],
            ['Ten' => 'Phước An','id_Tuyen' => '56'],
            ['Ten' => "M'Đrắk",'id_Tuyen' => '56'],
            ['Ten' => 'Krông Năng','id_Tuyen' => '56'],
            ['Ten' => 'Krông Bông','id_Tuyen' => '56'],
            ['Ten' => 'Easup','id_Tuyen' => '56'],
            ['Ten' => 'Eakar','id_Tuyen' => '56'],
            ['Ten' => 'Eahleo','id_Tuyen' => '56'],
            ['Ten' => "Cư M'gar",'id_Tuyen' => '56'],
            ['Ten' => 'Buôn Trấp','id_Tuyen' => '56'],
            ['Ten' => 'Buôn Đôn','id_Tuyen' => '56'],
            ['Ten' => 'Phía Nam Buôn Ma Thuột','id_Tuyen' => '56'],
            ['Ten' => 'Buôn Hồ','id_Tuyen' => '56'],
            ['Ten' => 'Quyết Thắng (Krông Pắk)','id_Tuyen' => '115'],
            ['Ten' => 'TP. Buôn Ma Thuột','id_Tuyen' => '115'],
            ['Ten' => 'Phước An','id_Tuyen' => '115'],
            ['Ten' => "M'Đrắk",'id_Tuyen' => '115'],
            ['Ten' => 'Krông Năng','id_Tuyen' => '115'],
            ['Ten' => 'Krông Bông','id_Tuyen' => '115'],
            ['Ten' => 'Easup','id_Tuyen' => '115'],
            ['Ten' => 'Eakar','id_Tuyen' => '115'],
            ['Ten' => 'Eahleo','id_Tuyen' => '115'],
            ['Ten' => "Cư M'gar",'id_Tuyen' => '115'],
            ['Ten' => 'Buôn Trấp','id_Tuyen' => '115'],
            ['Ten' => 'Buôn Đôn','id_Tuyen' => '115'],
            ['Ten' => 'Phía Nam Buôn Ma Thuột','id_Tuyen' => '115'],
            ['Ten' => 'Buôn Hồ','id_Tuyen' => '115'],

            ['Ten' => 'Tuy Đức','id_Tuyen' => '57'],
            ['Ten' => 'Quảng Sơn (Đắk Nông)','id_Tuyen' => '57'],
            ['Ten' => 'Quảng Khê','id_Tuyen' => '57'],
            ['Ten' => 'Đắk Mil','id_Tuyen' => '57'],
            ['Ten' => 'Krông Nô','id_Tuyen' => '57'],
            ['Ten' => "Đắk R'lấp (Kiến Đức)",'id_Tuyen' => '57'],
            ['Ten' => 'Gia Nghĩa','id_Tuyen' => '57'],
            ['Ten' => 'Cư Jút','id_Tuyen' => '57'],
            ['Ten' => 'Tuy Đức','id_Tuyen' => '116'],
            ['Ten' => 'Quảng Sơn (Đắk Nông)','id_Tuyen' => '116'],
            ['Ten' => 'Quảng Khê','id_Tuyen' => '116'],
            ['Ten' => 'Đắk Mil','id_Tuyen' => '116'],
            ['Ten' => 'Krông Nô','id_Tuyen' => '116'],
            ['Ten' => "Đắk R'lấp (Kiến Đức)",'id_Tuyen' => '116'],
            ['Ten' => 'Gia Nghĩa','id_Tuyen' => '116'],
            ['Ten' => 'Cư Jút','id_Tuyen' => '116'],

            ['Ten' => 'Điện Biên','id_Tuyen' => '58'],
            ['Ten' => 'Điện Biên','id_Tuyen' => '117'],

            ['Ten' => 'Xuân Lữ','id_Tuyen' => '59'],
            ['Ten' => 'Xuân Lộc','id_Tuyen' => '59'],
            ['Ten' => 'Xuân Bắc','id_Tuyen' => '59'],
            ['Ten' => 'Tân Phú','id_Tuyen' => '59'],
            ['Ten' => 'Sông Ray','id_Tuyen' => '59'],
            ['Ten' => 'Phú Cường','id_Tuyen' => '59'],
            ['Ten' => 'Định Quán','id_Tuyen' => '59'],
            ['Ten' => 'Nam Cát Tiên','id_Tuyen' => '59'],
            ['Ten' => 'Lý Lịch','id_Tuyen' => '59'],
            ['Ten' => 'Long Khánh','id_Tuyen' => '59'],
            ['Ten' => 'Lang Minh','id_Tuyen' => '59'],
            ['Ten' => 'Gia Ray','id_Tuyen' => '59'],
            ['Ten' => 'Căn Cứ 3','id_Tuyen' => '59'],
            ['Ten' => 'Cẩm Đường','id_Tuyen' => '59'],
            ['Ten' => 'Cẩm Mỹ','id_Tuyen' => '59'],
            ['Ten' => 'Bảo Bình','id_Tuyen' => '59'],
            ['Ten' => 'Xuân Lữ','id_Tuyen' => '118'],
            ['Ten' => 'Xuân Lộc','id_Tuyen' => '118'],
            ['Ten' => 'Xuân Bắc','id_Tuyen' => '118'],
            ['Ten' => 'Tân Phú','id_Tuyen' => '118'],
            ['Ten' => 'Sông Ray','id_Tuyen' => '118'],
            ['Ten' => 'Phú Cường','id_Tuyen' => '118'],
            ['Ten' => 'Định Quán','id_Tuyen' => '118'],
            ['Ten' => 'Nam Cát Tiên','id_Tuyen' => '118'],
            ['Ten' => 'Lý Lịch','id_Tuyen' => '118'],
            ['Ten' => 'Long Khánh','id_Tuyen' => '118'],
            ['Ten' => 'Lang Minh','id_Tuyen' => '118'],
            ['Ten' => 'Gia Ray','id_Tuyen' => '118'],
            ['Ten' => 'Căn Cứ 3','id_Tuyen' => '118'],
            ['Ten' => 'Cẩm Đường','id_Tuyen' => '118'],
            ['Ten' => 'Cẩm Mỹ','id_Tuyen' => '118'],
            ['Ten' => 'Bảo Bình','id_Tuyen' => '118'],
        ]);
    }
}
